import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import Themes from "@/app/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const discoFont = localFont({
  src: [
    {
      path: "./fonts/Mexcellent Rg.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-disco",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${discoFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Themes>
          <Header />
          {children}
          <Footer />
        </Themes>
      </body>
    </html>
  );
}
